StartupEvents.registry("item",event=>{
    event.create(regIds.crushbone);
    event.create(regIds.redstone_dust);
    event.create(regIds.iron_dust);
    event.create(regIds.iron_frame);
    event.create(regIds.white_dust);
    event.create(regIds.iron_mesh);
    event.create(regIds.iron_timber_sheet);
    event.create(regIds.raffle_ticket);
    event.create(regIds.reinforce_iron_sheet);
})