StartupEvents.registry("item",event=>{
    event.create(regIds.crushbone,"basic");
    event.create(regIds.redstone_dust,"basic");
    event.create(regIds.iron_dust,"basic");
    event.create(regIds.iron_frame,"basic");
    event.create(regIds.white_dust,"basic");
    event.create(regIds.iron_mesh,"basic");
    event.create(regIds.iron_timber_sheet,"basic");
    event.create(regIds.raffle_ticket,"basic");
})