const modid = "meng";
const namespace = modid + ":";
const regIds = {
    crushbone : namespace + "crushbone",
    redstone_dust : namespace + "redstone_dust",
    iron_dust : namespace + "iron_dust",
    crushbone_axe : namespace + "crushbone_axe",
    crushbone_sword : namespace + "crushbone_sword",
    iron_frame : namespace + "iron_frame",
    white_dust : namespace + "white_dust",
    iron_mesh : namespace + "iron_mesh",
    iron_timber_sheet : namespace + "iron_timber_sheet",
    iron_acacia_block : namespace + "iron_acacia_block",
    iron_birch_block : namespace + "iron_birch_block",
    iron_cherry_block : namespace + "iron_cherry_block",
    iron_crimson_block : namespace + "iron_crimson_block",
    iron_dark_oak_block : namespace + "iron_dark_oak_block",
    iron_jungle_block : namespace + "iron_jungle_block",
    iron_mangrove_block : namespace + "iron_mangrove_block",
    iron_oak_block : namespace + "iron_oak_block",
    iron_spruce_block : namespace + "iron_spruce_block",
    iron_warped_block : namespace + "iron_warped_block",
    raffle_ticket : namespace + "raffle_ticket",
    reinforce_iron_sheet : namespace + 'reinforce_iron_sheet',
    rain_doll : namespace + "rain_doll",
    sunny_doll : namespace + "sunny_doll",
    lava_debris : namespace + "lava_debris",
    lavl_chunk : namespace + "lavl_chunk",
    drill_bit : namespace + "drill_bit",
    saw_blade : namespace + "saw_blade",
    harvesting_accessories : namespace + "harvesting_accessories",
    stalinite_block : namespace + "stalinite_block",
    machine_incomplete : namespace + "machine_incomplete",
};