MekRecipe.infusionConversion(MekInfuse.alloyInfused,20,'mekanism:alloy_infused')
MekRecipe.infusionConversion(MekInfuse.alloyReinforced,20,'mekanism:alloy_reinforced')
MekRecipe.infusionConversion(MekInfuse.alloyAtomic,20,'mekanism:alloy_atomic')
MekRecipe.infusionConversion(MekInfuse.dragonBreath,10,'minecraft:dragon_breath')
MekRecipe.infusionConversion(MekInfuse.dragonBreath,10000,'minecraft:dragon_head')
MekRecipe.infusionConversion(MekInfuse.dragonBreath,1000,'minecraft:dragon_egg')